CREATE TABLE IF NOT EXISTS stg.stg_user (
    user_id TEXT,
    name TEXT,
    review_count INT,
    yelping_since TIMESTAMP,
    friends TEXT,
    useful INT,
    funny INT,
    cool INT,
    fans INT,
    elite TEXT,
    average_stars NUMERIC(3,2),
    compliment_hot INT,
    compliment_more INT,
    compliment_profile INT,
    compliment_cute INT,
    compliment_list INT,
    compliment_note INT,
    compliment_plain INT,
    compliment_cool INT,
    compliment_funny INT,
    compliment_writer INT,
    compliment_photos INT
);
